# Generated by Django 4.2.6 on 2023-10-23 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='name',
        ),
        migrations.RemoveField(
            model_name='url',
            name='url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='url',
        ),
        migrations.AddField(
            model_name='url',
            name='longUrl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='shortUrl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_app.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
