# Generated by Django 4.2.6 on 2023-10-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_remove_url_name_remove_url_url_remove_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
